CREATE DATABASE paybd;
USE paybd;
CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
phone VARCHAR(20) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
profileImg VARCHAR(255) DEFAULT 'img/default-profile.jpg'
);
